### ISSUE TITLE
Cannot run any examples

### ISSUE THREAD

**Issue by feynmanliang** [facebookresearch/pplbench#59]
### Issue Description

I cannot run any of the examples under `examples/*.json`

### Steps to Reproduce

Following the Getting Started section of the README:

```sh
pip install pplbench[ppls]
pplbench examples/example.json
```

I get a JSON serializability error:

```sh
(base) root@df1b9c39af04:~/work/pplbench# pplbench examples/example.json 
Traceback (most recent call last):
  File "/opt/conda/bin/pplbench", line 8, in <module>
    sys.exit(console_main())
  File "/opt/conda/lib/python3.8/site-packages/pplbench/__main__.py", line 12, in console_main
    main()
  File "/opt/conda/lib/python3.8/site-packages/pplbench/main.py", line 113, in main
    output_dir = utils.create_output_dir(config)
  File "/opt/conda/lib/python3.8/site-packages/pplbench/lib/utils.py", line 63, in create_output_dir
    fp.write(SimpleNamespaceEncoder().encode(config))
  File "/opt/conda/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/conda/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/conda/lib/python3.8/site-packages/pplbench/lib/utils.py", line 45, in default
    return json.JSONEncoder.default(self, object)
  File "/opt/conda/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Namespace is not JSON serializable
```

### Expected Behavior

I expect for PPLBench to execute the example and report the results.

### System Info
Please provide information about your setup
- PyTorch Version (run `print(torch.__version__)`: 1.7.0
- Python version: 3.8.6, also reproduced on 3.6 (e.g. https://github.com/facebookresearch/pplbench/runs/1671648775?check_suite_focus=true)

**Comment by horizon-blue** [comment]
Thanks for raising the issue. It should be fixed in #61  :D
